- name: "add java8 repository"
  sudo: yes
  template: src=java-8-debian.list.j2 dest=/etc/apt/sources.list.d/java-8-debian.list

- name: "add key for apt"
  sudo: yes
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EEA14886

- name: auto accept oracle jdk license
  sudo: yes
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: "install java 8"
  sudo: yes
  apt: name=oracle-java8-installer update_cache=yes

- name: "install java 8 defaults"
  sudo: yes
  apt: name=oracle-java8-set-default
